### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by 8hatch8** [8hatch8/furima-37275#21]
# URL
https://furima-37275.herokuapp.com/

# Basic認証
- ID: `yutaka8pg`
- PASS: `0724`

# 出品者
- Email: `test@test.com`
- PASS: `a111111`

# 購入者
- Email: `test@test2.com`
- PASS: `a222222`

**Comment by snkw-works** [comment]
@8hatch8 さん、お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [ ] **編集ページ下部の「もどる」ボタンを押すと、編集途中の情報は破棄され、「商品詳細表示ページ」に遷移するよう修正しましょう**
「もどる」ボタンをクリックすると、商品詳細表示ページではなくトップページに遷移してしまいます。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by 8hatch8** [comment]
@snkw-works ご確認ありがとうございます！
部分テンプレート変更後の確認が不十分でした、申し訳ございません
修正いたします

**Comment by miyu-yamamoto** [comment]
@8hatch8 さん、フリマアプリ達成要件分の開発お疲れ様でした！
正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！

＜今後の学習例＞
・フリマアプリ追加実装
・オリジナルアプリ開発
・今まで学んできた言語あるいは新言語の学習　等
今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。
また、以下提出物に関するリマインドです。

＜提出物＞
・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
※提出期日については、最終課題開始時に配布した下記動画にてご確認いただきますようお願いいたします。

＜最終課題に関する締め切りについての動画＞
https://master.tech-camp.in/curriculums/7106

今後の流れに関して、もしご不明点がございましたら、
担当ライフコーチまでお気兼ねなくお申し付けくださいませ。
![最終課題LGTM](https://user-images.githubusercontent.com/59544869/146704634-e3cfe7d3-7eba-4e84-8656-10d361667d6c.png)

**Comment by 8hatch8** [comment]
@miyu-yamamoto
ご確認ありがとうございました！
ライフコーチやメンターさんのおかげでここまでこれました
ありがとうございます！

引き続きどうぞよろしくお願いいたします
